// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DatepickerController from "./datepicker_controller"
application.register("datepicker", DatepickerController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import LocationFiltersController from "./location_filters_controller"
application.register("location-filters", LocationFiltersController)

import PopoverController from "./popover_controller"
application.register("popover", PopoverController)
