// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DatepickerController from "./datepicker_controller"
application.register("datepicker", DatepickerController)

import DayTabsController from "./day_tabs_controller"
application.register("day-tabs", DayTabsController)

import DropdownSelectController from "./dropdown_select_controller"
application.register("dropdown-select", DropdownSelectController)

import GrainyGradientController from "./grainy_gradient_controller"
application.register("grainy-gradient", GrainyGradientController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import LocationFiltersController from "./location_filters_controller"
application.register("location-filters", LocationFiltersController)

import PopoverController from "./popover_controller"
application.register("popover", PopoverController)

import TripFiltersController from "./trip_filters_controller"
application.register("trip-filters", TripFiltersController)
