// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DatepickerController from "./datepicker_controller"
application.register("datepicker", DatepickerController)

import DayTabsController from "./day_tabs_controller"
application.register("day-tabs", DayTabsController)

import DropdownSelectController from "./dropdown_select_controller"
application.register("dropdown-select", DropdownSelectController)

import GrainyGradientController from "./grainy_gradient_controller"
application.register("grainy-gradient", GrainyGradientController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import LocationFiltersController from "./location_filters_controller"
application.register("location-filters", LocationFiltersController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import PasswordToggleController from "./password_toggle_controller"
application.register("password-toggle", PasswordToggleController)

import PopoverController from "./popover_controller"
application.register("popover", PopoverController)

import RadioAccordionController from "./radio_accordion_controller"
application.register("radio-accordion", RadioAccordionController)

import ToastNotificationController from "./toast_notification_controller"
application.register("toast-notification", ToastNotificationController)

import TripFiltersController from "./trip_filters_controller"
application.register("trip-filters", TripFiltersController)
